### ISSUE TITLE
How difficult would it be to add Facebook SDK using the xcode-exec script?

### ISSUE THREAD

**Issue by sanketsahusoft** [rainforestapp/rnfrst-xcode#1]
Thanks for writing this library. I am wondering if we can extend the functionality of this repo to easily add other frameworks to iOS code as well.

**Comment by marianafranco** [comment]
Hi @sanketsahusoft, should not be complicated to change this repo to add support for other frameworks. 

Btw, the `xcode-exec` script is already generic. It updates the `project.pbxproj` adding the framework file to the `Frameworks` and `Embed Framework` groups. 

I believe that it's not necessary to add the Facebook SDK as an "embedded binary", so in this case you will need to tweak a little the `xcode-exec` script to remove the part that adds the file to the `Embed Framework` group.

**Comment by sanketsahusoft** [comment]
Thanks for your help @marianafranco.

We are using `xcode-exec` at the moment and its working well. I will check your suggestion about removing the part of the code which adds the SDK as "embedded binary" from `xcode-exec`.

👍
